// src/public/js/vue/ChatBody.vue
<template>
    <div class="chat-body" ref="body">
        <div class="chat-message" :class="{'chat-message-self': message.position === 'self'}"
             v-for="message in messages">
            <div v-if="message.type === 'text'">
                {{message.content}}
            </div>
            <div v-else-if="message.type === 'template'">
                <button class="btn btn-default btn-block" v-for="item in message.items"
                        @click="$emit('button-action', item)">
                    {{item.text}}
                </button>
            </div>
            <div class="chat-meta">
                {{message.user}}
            </div>
        </div>
    </div>
</template>
<script>
    export default {
        data() {
            return {}
        },
        props: {
            messages: null
        },
        updated(){
            // Automatically scroll the body to latest message
            this.$refs.body.scrollTop = this.$refs.body.scrollHeight;
        }
    }
</script>

// src/public/js/react/components/chat/ChatBody.jsx
import React from "react";
import {connect} from "react-redux";

const mapStateToProps = state => {
    return {
        messages: state.chat.messages
    };
};
const mapDispatchToProps = dispatch => {
    return {
        setInput(input) {
            dispatch({
                type: 'SET_INPUT',
                payload: input
            });
        }
    }
};

export default connect(mapStateToProps, mapDispatchToProps)(class ChatBody extends React.Component {
    render() {
        return (
            <div className="chat-body" ref={el => this.body = el}>
                {this.listMessages()}
            </div>
        )
    }

    componentDidUpdate(){
        this.body.scrollTop = this.body.scrollHeight;
    }

    listMessages() {
        const listButtons = (buttons) => {
            return buttons.map((button, index) => {
                return (
                    <button type="button" className="btn btn-default btn-block" key={index}
                            onClick={() => this.props.setInput(button.text)}>
                        {button.text}
                    </button>
                )
            });
        };
        return this.props.messages.map((message, index) => {
            if (message.type === 'text') {
                return (
                    <div className={
                        'chat-message ' +
                        (message.position === 'self' ? 'chat-message-self ' : ' ')
                    } key={index}>
                        {message.content}
                        <div className="chat-meta">
                            {message.user}
                        </div>
                    </div>
                )
            }
            if (message.type === 'template') {
                return (
                    <div className={
                        'chat-message ' +
                        (message.position === 'self' ? 'chat-message-self ' : ' ')
                    } key={index}>
                        {listButtons(message.items)}
                        <div className="chat-meta">
                            {message.user}
                        </div>
                    </div>
                )
            }
        });
    }
});
